# Generated by Django 5.0.6 on 2024-05-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionvalue',
            name='is_extended',
        ),
    ]
