# Generated by Django 5.0.6 on 2024-05-10 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0001_initial'),
        ('option', '0002_remove_optionvalue_is_extended'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(blank=True, max_length=256, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postoptions', to='option.option')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postoptions', to='avto.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postoptionvalues', to='option.optionvalue')),
                ('post_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postoptionvalues', to='option.postoption')),
            ],
            options={
                'unique_together': {('post_option', 'option_value')},
            },
        ),
    ]
