# Generated by Django 5.0.6 on 2024-05-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0004_option_is_filter_option_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionvalue',
            name='code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
