# Generated by Django 5.0.6 on 2024-05-12 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0005_optionvalue_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionValueExtendedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(blank=True, max_length=256, null=True)),
                ('option_value_extended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optionvalueextendedvalue', to='option.optionvalueextended')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
