# Generated by Django 5.0.6 on 2024-05-12 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0002_post_main_photo'),
        ('option', '0006_optionvalueextendedvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='optionvalueextended',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='option.optionvalueextended'),
        ),
        migrations.AddField(
            model_name='postoptionvalue',
            name='option_value_extended',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='option.optionvalueextended'),
        ),
        migrations.AlterField(
            model_name='optionvalueextended',
            name='option_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_extended', to='option.optionvalue'),
        ),
        migrations.AlterField(
            model_name='postoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='option.option'),
        ),
        migrations.AlterField(
            model_name='postoption',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='avto.post'),
        ),
        migrations.AlterField(
            model_name='postoptionvalue',
            name='option_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.optionvalue'),
        ),
        migrations.AlterField(
            model_name='postoptionvalue',
            name='post_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='option.postoption'),
        ),
        migrations.DeleteModel(
            name='OptionValueExtendedValue',
        ),
    ]
