# Generated by Django 5.0.6 on 2024-05-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_photo',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=''),
        ),
    ]
